version: '3'

services:

  elements1:
    env_file: .env
    build:
      context: ./elements
      args:
        ELEMENTS_VER: $ELEMENTS_VER
    image: elements:$ELEMENTS_VER
    container_name: elements1
    hostname: elements1
    ports:
      - "20001:18443"
    networks:
      - elements-local-network
    command: >
      /bin/bash -c "
        elementsd \
          -regtest \
          -port=10001 \
          -connect=elements2:10002 &&
        tail -f /dev/null"

  elements2:
    env_file: .env
    build:
      context: ./elements
      args:
        ELEMENTS_VER: $ELEMENTS_VER
    image: elements:$ELEMENTS_VER
    container_name: elements2
    hostname: elements2
    ports:
      - "20002:18443"
    networks:
      - elements-local-network
    command: >
      /bin/bash -c "
        elementsd \
          -regtest \
          -port=10002 \
          -connect=elements1:10001 &&
        tail -f /dev/null"

networks:
  elements-local-network:
    external: true
